version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
    post_install:
      - VIRTUAL_ENV="$READTHEDOCS_VIRTUALENV_PATH" poetry install --with dev

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
