version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config --local virtualenvs.create false
    post_install:
      - which sphinx-build
      - sphinx-build --version
      - poetry install --with dev
      - ls -lah
      - pwd
      - which sphinx-build
      - sphinx-build --version

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
