name: Continuous Integration

on:
  push:

jobs:

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.6]
    runs-on: "${{matrix.os}}"
    env:
      PY_COLORS: 1
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Install Python, uses: actions/setup-python@v2, with: {python-version: "${{matrix.python}}"}, id: py}
      - run: python3 setup.py sdist
      - run: set -x && ls -lah && ls -lah dist/ && tar -tzf dist/*.tar.gz
      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.LEGACY_PYPI_API_TOKEN }}
